### ISSUE TITLE
Cannot read property 'transfer-encoding' of undefined - multiparty

### ISSUE THREAD

**Issue by Ikhan** [pillarjs/multiparty#169]
I have a code below, and it was working for with only one file field. But i wanted to add more details on to it.  I added multiparty and its its giving above error. 

Hope someone could help me on this. Thanks.

          var storage = multer.diskStorage({
                            destination: function(req, file, cb){
                                cb(null, './uploads'); 
                                       console.log(file); 
                            },
                            filename: function(req, file, cb){
                                cb(null, file.image[0].fieldName + '-' + Date.now() + '.jpg');                
                            }
                        });
      var upload = multer({storage:storage}).single('image');

      create: function(req,res){   

              var form = new multiparty.Form();

              form.parse(req, function(err, fields, file) {
              req.body = fields;

              let name = req.body.name;
              let email = req.body.email;

             upload(file, res, function(err){
              if(err) {
                console.log(err)
              }
              else {
                console.log('no error');
              }
            })
        }

**Comment by dougwilson** [comment]
Hi @Ikhan there isn't enough information provided her to really understand where your issue is. Can you provide the following?

1. The version of Node.js you are using
2. The version of this module you are using
3. The full stack trace of the error message you are getting?

**Comment by Ikhan** [comment]
@dougwilson Thank you for asking those infos. 

node version : v6.10.0
multiparty:  ^4.1.3,
multer: *

full stack trace : 

<img width="1197" alt="screen shot 2017-03-19 at 2 21 24 pm" src="https://cloud.githubusercontent.com/assets/475993/24083553/63b7061c-0caf-11e7-8d92-2f488b5526dc.png">

**Comment by dougwilson** [comment]
Hi @Ikhan thanks for that! The error is coming from your `multer` usage; there is nothing from this module in the stack trace.

**Comment by dougwilson** [comment]
I can, though, take a look deeper if you like, but would need the additional following information:

1. The complete Node.js app that I can run on my machine.
2. Complete instructions on how to call the app to reproduce the above error.

**Comment by dougwilson** [comment]
Looking at your code and the `multer` source code, you are storing the function from https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L17 in your `upload` variable in your code above. That function expects the `req` object as the first argument, but you are passing in the `file` argument, which it wasn't expecting, resulting in the error you are seeing.

**Comment by Ikhan** [comment]
@dougwilson Thanks for pointing that out. I even correct that but still gives me that error. 

as far as I know, multer is looking for encoding type and mutiparty not returning any encoding. Below is the screen cap of what returns from multiparty

<img width="925" alt="screen shot 2017-03-19 at 2 42 26 pm" src="https://cloud.githubusercontent.com/assets/475993/24083704/a2dfa2ba-0cb2-11e7-9b9d-73e0f34cdda5.png">

And this is what return from multer.

<img width="388" alt="screen shot 2017-03-19 at 2 42 54 pm" src="https://cloud.githubusercontent.com/assets/475993/24083707/addb2aea-0cb2-11e7-80d8-d7eb48dce099.png">

correct me if I am wrong. Thanks.

**Comment by dougwilson** [comment]
HI @Ikhan I'm not sure what you're trying to achieve, but both `multer` and `multiparty` are only designed to read the original request. You're using `multer` in a way it was never designed for, which is you are trying to pump in a `FileStream` into it, which will never work. It will only accept the `req` as the first argument.

**Comment by dougwilson** [comment]
Basically, you should be using _either_ `multer` or `multiparty`; you cannot use both at the same time unless at least one of them are redesigned; they are mutually exclusive.

**Comment by Ikhan** [comment]
@dougwilson Thanks , issue was I was using the both the modules for no-reason. Thanks @dougwilson

**Comment by bimalgrg519** [comment]
@dougwilson Thanks, i was sending res object in place of req :D

**Comment by jungjuyoung** [comment]
I met the same error as @Ikhan .
Are you guys sure there's a solution? The codes below are my error codes

TypeError: Cannot read property 'transfer-encoding' of undefined
[0]     at hasbody (/Users/jungjuyoung/dev/react-shopping-mall/node_modules/type-is/index.js:93:21)
[0]     at typeofrequest (/Users/jungjuyoung/dev/react-shopping-mall/node_modules/type-is/index.js:127:8)
[0]     at multerMiddleware (/Users/jungjuyoung/dev/react-shopping-mall/node_modules/multer/lib/make-middleware.js:18:10)
[0]     at router.post (/Users/jungjuyoung/dev/react-shopping-mall/server/routes/product.js:34:3)
[0]     at Layer.handle [as handle_request] (/Users/jungjuyoung/dev/react-shopping-mall/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/jungjuyoung/dev/react-shopping-mall/node_modules/express/lib/router/route.js:137:13)
[0]     at User.findByToken (/Users/jungjuyoung/dev/react-shopping-mall/server/middleware/auth.js:16:5)
[0]     at /Users/jungjuyoung/dev/react-shopping-mall/server/models/User.js:86:13
[0]     at /Users/jungjuyoung/dev/react-shopping-mall/node_modules/mongoose/lib/model.js:4837:16
[0]     at /Users/jungjuyoung/dev/react-shopping-mall/node_modules/mongoose/lib/model.js:4837:16
[0]     at /Users/jungjuyoung/dev/react-shopping-mall/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
[0]     at /Users/jungjuyoung/dev/react-shopping-mall/node_modules/mongoose/lib/model.js:4860:21
[0]     at _hooks.execPost (/Users/jungjuyoung/dev/react-shopping-mall/node_modules/mongoose/lib/query.js:4370:11)
[0]     at /Users/jungjuyoung/dev/react-shopping-mall/node_modules/kareem/index.js:135:16
[0]     at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by shruthigss** [comment]
Can you help to solve this error @Ikhan 
 
Cannot read properties of undefined (reading 'transfer-encoding')
    at hasbody (C:\Users\Admin\Desktop\instaclone\server\node_modules\type-is\index.js:93:21)
    at typeofrequest (C:\Users\Admin\Desktop\instaclone\server\node_modules\type-is\index.js:127:8)
    at multerMiddleware (C:\Users\Admin\Desktop\instaclone\server\node_modules\multer\lib\make-middleware.js:13:10)
    at C:\Users\Admin\Desktop\instaclone\server\index.js:36:5
    at Layer.handle [as handle_request] (C:\Users\Admin\Desktop\instaclone\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Admin\Desktop\instaclone\server\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\Admin\Desktop\instaclone\server\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\Admin\Desktop\instaclone\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Admin\Desktop\instaclone\server\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Admin\Desktop\instaclone\server\node_modules\express\lib\router\index.js:346:12)
