### ISSUE TITLE
Request aborted

### ISSUE THREAD

**Issue by metalpapa** [pillarjs/multiparty#181]
Hi. since long time in the error log of my production server(middleware), I have the following error, I have not been able to replicate the error in development. and I do not understand why it happens.
Any help would appreciate it.

```
 [2017-10-17 09:58:52,840] [ERROR] [137.84 MB][application:630        ] Error: Request aborted
    at IncomingMessage.onReqAborted (/home/node/********/node_modules/multiparty/index.js:183:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:283:11)
    at Socket.serverSocketCloseListener (_http_server.js:296:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
[2017-10-17 10:02:19,470] [ERROR] [137.47 MB][application:630        ] Error: Request aborted
    at IncomingMessage.onReqAborted (/home/node/********/node_modules/multiparty/index.js:183:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:283:11)
    at Socket.serverSocketCloseListener (_http_server.js:296:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
[2017-10-17 10:16:57,774] [ERROR] [205.87 MB][application:630        ] Error: Request aborted
    at IncomingMessage.onReqAborted (/home/node/********/node_modules/multiparty/index.js:183:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:283:11)
    at Socket.serverSocketCloseListener (_http_server.js:296:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

#### Framework 
     none
#### System:
    Node              : v6.11.1
    npm               : 3.10.10
    OS                :  Windows 7 x64
#### Dependencies
```{
		"body-parser": "^1.16.0",
		"connect-multiparty": "^2.0.0",
		"console-stamp": "^0.2.5",
		"crypto-js": "^3.1.8",
		"express": "^4.14.0",
		"express-http-proxy": "^0.11.0",
		"file-api": "^0.10.4",
		"glob": "^7.1.1",
		"lodash": "^4.17.4",
		"moment": "^2.17.1",
		"multer": "^1.2.1",
		"q": "^1.4.1",
		"request": "^2.79.0",
		"socket.io": "^1.7.3",
		"stack-trace": "0.0.9",
		"uuid": "^3.0.1"
      "devDependencies": {
		"del": "^2.2.2",
		"gulp": "^3.9.1",
		"gulp-zip": "^4.0.0",
		"pump": "^1.0.2"
	}
```

**Comment by dougwilson** [comment]
Hi @metalpapa the error is just from the `'aborted'` event in the Node.js (see the Node.js docs: https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_aborted). The event is Node.js telling this module that the socket is closed before the request finished, which is an error. Not sure how you replicate it; that would probably be a question to the Node.js core team on how to reproduce the conditions under which that event is emitted.

**Comment by metalpapa** [comment]
@dougwilson ok thank.

**Comment by ShepelE** [comment]
**metalpapa**, I get the same error
Error: Request aborted
    at IncomingMessage.onReqAborted (/home/node/********/node_modules/multiparty/index.js:183:17)

I have one case for you:
if you use **axios** and you have set timeout for requests (like axios.defaults.timeout = 1000; ) somewhere in your app, then axios will close connection in 1 sec and your api will get this error.
So, if you use axios, you should probably start from increasing time to process file uploading - for file upload request set it's own timeout like
axios.request({
...
method: 'post',
timeout: 60000,
...
});
And don't forget to handle aborting error from multiparty in your api. figuring out how...
