### ISSUE TITLE
os.tmpDir seems to be incompatible with Windows

### ISSUE THREAD

**Issue by lubanproj** [pillarjs/multiparty#238]
windows version：windows 10 
node version：v14.15.3
npm version：6.14.9

TypeError: os.tmpDir is not a function
    at new Form (C:\souce_code\Uploader\samples\Node.js\node_modules\multiparty\index.js:55:44)
    at multipart (C:\souce_code\Uploader\samples\Node.js\node_modules\connect-multiparty\index.js:56:16)
    at Layer.handle [as handle_request] (C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\layer.js:95:5)
    at C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\index.js:335:12)
    at next (C:\souce_code\Uploader\samples\Node.js\node_modules\express\lib\router\index.js:275:10)
    at serveStatic (C:\souce_code\Uploader\samples\Node.js\node_modules\serve-static\index.js:75:16)
) Pause upload Cancel upload

**Comment by dougwilson** [comment]
You are using an older version of this module. The current version of this module does not use `os.tmpDir`.

**Comment by lubanproj** [comment]
ok thanks
