### ISSUE TITLE
Error while uploading multiple files on S3 using s3.js example.

### ISSUE THREAD

**Issue by janakkansal** [pillarjs/multiparty#49]
I am trying to upload multiple files using S3 example on Amazon S3 using streams without touching hard drive. It works for single file but fails in case of multiple file selection. In following code I am using 'multiple' attribute with file input to select one or more files for uploading.

``` javascript

var http = require('http')
    , util = require('util')
    , multiparty = require('multiparty')
    , knox = require('knox')
    , Batch = require('batch')
    , PORT = process.env.PORT || 27372

var s3Client = knox.createClient({
    secure: false,
    key: '',
    secret: '',
    bucket: ''
});

var server = http.createServer(function(req, res) {
    if (req.url === '/') {
        res.writeHead(200, {'content-type': 'text/html'});
        res.end(
            '<form action="/upload" enctype="multipart/form-data" method="post">'+
                '<input type="file" name="upload" multiple><br>'+
                '<input type="submit" value="Upload">'+
                '</form>'
        );
    } else if (req.url === '/upload') {
        var headers = {
            'x-amz-acl': 'public-read'
        };
        var form = new multiparty.Form();
        var batch = new Batch();
        batch.push(function(cb) {
            form.on('part', function(part) {
                if (! part.filename) return;
                cb(null, part);
            });
        });
        batch.end(function(err, results) {
            if (err) throw err;
            form.removeListener('close', onEnd);
            var destPath = '/'+results[0].filename
                , part = results[0];
            headers['Content-Length'] = part.byteCount;
            s3Client.putStream(part, destPath, headers, function(err, s3Response) {
                if (err) throw err;
                res.statusCode = s3Response.statusCode;
                s3Response.pipe(res);
                console.log("https://s3.amazonaws.com/testcmsresource" + destPath);
            });
        });
        form.on('close', onEnd);
        form.parse(req);
    } else {
        res.writeHead(404, {'content-type': 'text/plain'});
        res.end('404');
    }
    function onEnd() {
        throw new Error("no uploaded file");
    }
});
server.listen(PORT, function() {
    console.info('listening on http://0.0.0.0:'+PORT+'/');
});


```

If I select single file then it works fine otherwise it fails with following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Request aborted
    at IncomingMessage.onReqAborted (G:\Projects\nodejs\Test\node_modules\multiparty\index.js:131:17)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at abortIncoming (http.js:1911:11)
    at Socket.serverSocketCloseListener (http.js:1923:5)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)

```

Kindly suggest how multiple files can be uploaded to S3 without touching to hard drive.

**Comment by ChrisGrigg** [comment]
Getting a signed url and uploading direct from the client worked really badly for me. Fine in Chrome but in Firefox and Safari I had issues with strange filenames (maybe need encode the url) and larger file sizes.
